# Generated by Django 5.2.7 on 2025-12-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descrition',
            new_name='description',
        ),
    ]
