# Generated by Django 5.2.7 on 2026-01-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_descrition_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('happening', 'Happening Now'), ('finished', 'Finished')], default='upcoming', max_length=10),
        ),
    ]
